#!/usr/bin/env bash
#
# Motion Browser — Track B: fetch a Chromium checkout for the Motion fork.
#
# HONESTY (spec §77): this script performs a REAL Chromium fetch (~25–40 GB
# download, ~60–90 GB on disk after hooks, 1–3 h network-bound) and can ONLY
# run on a machine with Chromium-class resources — GitHub-hosted runners
# (~14 GB disk, 6 h cap) cannot. See docs/BUILD_CHROMIUM.md.
#
# What it does:
#   1. Creates the checkout at <motion-chromium>/chromium (gitignored).
#   2. `fetch --no-history android`  (= chromium + target_os += ['android']).
#   3. Records the upstream commit + versions into motion-chromium/VERSION_MOTION.
#   4. `gclient sync -D` to reconcile deps with the checked-out DEPS.
#
# Requirements: depot_tools on PATH (`fetch`, `gclient` must resolve).
# Env overrides:
#   MOTION_CHECKOUT_DIR   default: <script-dir>/../chromium
#   MOTION_SKIP_SYNC=1    skip the final `gclient sync -D`

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"          # motion-chromium/tools
MOTION_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"                       # motion-chromium
CHECKOUT_DIR="${MOTION_CHECKOUT_DIR:-${MOTION_ROOT}/chromium}"
SRC_DIR="${CHECKOUT_DIR}/src"

log() { printf '\n[motion-fetch] %s\n' "$*"; }
die() { printf '\n[motion-fetch] ERROR: %s\n' "$*" >&2; exit 1; }

for tool in git fetch gclient; do
  command -v "${tool}" >/dev/null 2>&1 \
    || die "'${tool}' not found on PATH. Install depot_tools and export it:" \
           "  git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git" \
           "  export PATH=\"\$HOME/tools/depot_tools:\$PATH\"   # see docs/BUILD_CHROMIUM.md §3"
done

# --- 1–2. Fetch --------------------------------------------------------------
if [ ! -d "${SRC_DIR}" ]; then
  log "fetching Chromium (no history, android target) into ${CHECKOUT_DIR}"
  log "this downloads tens of GB and takes 1–3 h on a fast connection"
  mkdir -p "${CHECKOUT_DIR}"
  cd "${CHECKOUT_DIR}"
  # 'fetch android' = chromium checkout with target_os += ['android'] in .gclient.
  fetch --no-history android
else
  log "existing checkout found at ${SRC_DIR} — skipping fetch"
fi

[ -d "${SRC_DIR}" ] || die "checkout missing after fetch: ${SRC_DIR}"
cd "${SRC_DIR}"

# --- 3. Record pinned state into VERSION_MOTION ------------------------------
UPSTREAM_COMMIT="$(git rev-parse HEAD)"

CHROMIUM_VERSION="unknown"
CHROME_VERSION_FILE="${SRC_DIR}/chrome/VERSION"
if [ -f "${CHROME_VERSION_FILE}" ]; then
  CHROMIUM_VERSION="$(awk -F= '/^(MAJOR|MINOR|BUILD|PATCH)=/ {printf "%s%s", sep, $2; sep="."}' \
    "${CHROME_VERSION_FILE}")"
fi

shopt -s nullglob
PATCH_FILES=( "${MOTION_ROOT}"/patches/*.patch )
shopt -u nullglob
PATCH_COUNT="${#PATCH_FILES[@]}"

{
  printf '# motion-chromium/VERSION_MOTION — GENERATED by tools/fetch_chromium.sh. Do not hand-edit.\n'
  printf 'chromium_version = "%s"\n' "${CHROMIUM_VERSION}"
  printf 'motion_patch_version = %s\n' "${PATCH_COUNT}"
  printf 'build_version = "%s-motion.%s"\n' "${CHROMIUM_VERSION}" "${PATCH_COUNT}"
  printf 'upstream_commit = "%s"   # git -C chromium/src rev-parse HEAD\n' "${UPSTREAM_COMMIT}"
  printf 'patches = [\n'
  for p in "${PATCH_FILES[@]}"; do
    printf '  "%s",\n' "$(basename "${p}")"
  done
  printf ']\n'
} > "${MOTION_ROOT}/VERSION_MOTION"

log "recorded ${MOTION_ROOT}/VERSION_MOTION:"
sed 's/^/    /' "${MOTION_ROOT}/VERSION_MOTION"

# --- 4. Sync -----------------------------------------------------------------
if [ "${MOTION_SKIP_SYNC:-0}" != "1" ]; then
  log "gclient sync -D (reconciles third_party with the checked-out DEPS)"
  gclient sync -D
else
  log "MOTION_SKIP_SYNC=1 — skipping gclient sync -D"
fi

log "done. Next: tools/apply_patches.sh (see docs/BUILD_CHROMIUM.md)."
